api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('get-assets/', views.get_assets, name='get_assets'),
    path('get-asset-groups/', views.get_asset_groups, name='get_asset_groups'),
    path('get-asset-types/', views.get_asset_types, name='get_asset_types'),
    path('get-markets/', views.get_markets, name='get_markets'),
    path('price-history/<str:code>/', views.price_history, name='price_history'),
]

cadastro/urls.py
from django.urls import path

from . import views

app_name = 'cadastro'
urlpatterns = [
    path('cadastro/', views.register_user, name='register'),
    path('login_user/', views.login_user, name='login'),
    path('perfil/', views.change_password, name='change_password'),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('invest.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/', include('cadastro.urls')),
    path('api/', include('api.urls')),
]

admin.site.site_title = 'Invest'# Site de administração do Django
admin.site.site_header = 'Administração Invest'# Administração do Django
# admin.site.index_title = 'Mapa do site'# Administração do Site

invest/urls.py
from django.urls import path

from . import views

app_name = 'invest'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('home/update_wallet', views.UpdateWalletView.as_view(), name='update_wallet'),
    path('home/update_content_value', views.UpdateContentValueView.as_view(), name='update_content_value'),
    path('investimentos/', views.ContentListView.as_view(), name='content_list'),
    path('investimentos/detail/<int:content_id>/', views.ContentDetailView.as_view(), name='content_detail'),
    path('investimentos/delete-content/<int:content_id>/', views.DeleteContentDetailView.as_view(), name='delete_content'),
    path('dividendos', views.DividendListView.as_view(), name='dividend_list'),
    path('dividendos/detail/<int:pk>/', views.DividendDetailView.as_view(), name='dividend_detail'),
]

invest/models.py
from django.db import models
from django.utils import timezone

from cadastro.models import User


class Market(models.Model):

    class Meta:
        verbose_name = 'Local'
        verbose_name_plural = 'Locais'

    name = models.CharField('Local', max_length=50)
    currency = models.CharField('Moeda', max_length=10)
    code = models.CharField('Código', max_length=10)
    symbol = models.CharField('Símbolo', max_length=10)
    yf_suffix = models.CharField('Sufixo Yahoo Finance', max_length=5, blank=True, null=True)

    def __str__(self):
        return self.name


class Bank(models.Model):

    class Meta:
        verbose_name = 'Banco'

    name = models.CharField('Nome do banco ou corretora', max_length=50)
    market = models.ForeignKey(Market, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class AssetType(models.Model):

    class Meta:
        verbose_name = 'Tipo de Investimento'
        verbose_name_plural = 'Tipos de Investimento'

    type = models.CharField('Tipo', max_length=50)

    def __str__(self):
        return self.type


class AssetGroup(models.Model):

    class Meta:
        verbose_name = 'Grupo de Investimento'
        verbose_name_plural = 'Grupos de Investimento'

    group = models.CharField('Grupo', max_length=50)

    def __str__(self):
        return self.group


class Asset(models.Model):

    SOURCE_CHOICES = [('MANUAL', 'Manual'), ('YF', 'Yahoo Finance')]

    class Meta:
        verbose_name = 'Ativo'

    name = models.CharField('Nome do ativo', max_length=50)
    description = models.CharField('Descrição', max_length=100)
    market = models.ForeignKey(Market, on_delete=models.CASCADE)
    type = models.ForeignKey(AssetType, on_delete=models.CASCADE)
    group = models.ForeignKey(AssetGroup, on_delete=models.CASCADE)
    expiration_date = models.DateTimeField('Vencimento', blank=True, null=True)
    source = models.CharField(
        'Fonte',
        max_length=10,
        choices=SOURCE_CHOICES
    )

    def __str__(self):
        if self.expiration_date is None:
            return self.name
        else:
            return self.name + ' | ' + self.expiration_date.strftime('%Y-%m-%d')


class Wallet(models.Model):

    class Meta:
        verbose_name = 'Carteira'

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dt_created = models.DateTimeField('Data de criação')
    dt_updated = models.DateTimeField('Data de atualização')

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        self.dt_updated = timezone.now()
        if update_fields is not None:
            update_fields = {'dt_updated'}.union(update_fields)

        super().save(
            force_insert=force_insert, force_update=force_update, using=using,
            update_fields=update_fields
        )

    def __str__(self):
        return self.user.email + ' | ' + self.dt_updated.strftime('%Y-%m-%d %H:%M:%S %Z')


class Content(models.Model):
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE)
    bank = models.ForeignKey(Bank, on_delete=models.CASCADE)
    quantity = models.FloatField('Quantidade')
    cost = models.FloatField('Custo')
    price = models.FloatField('Cotação')
    value = models.FloatField('Valor')
    dt_updated = models.DateField('Data de atualização')

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        self.value = self.quantity*self.price
        self.dt_updated = timezone.now()
        if update_fields is not None:
            update_fields = {'dt_updated'}.union(update_fields)
            if 'quantity' in update_fields or 'price' in update_fields:
                update_fields = {'value'}.union(update_fields)

        super().save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields
        )

    def __str__(self):
        return self.asset.name + ' | ' + self.bank.name


class MarketAgg(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    market = models.ForeignKey(Market, on_delete=models.CASCADE)
    cost = models.FloatField('Custo')
    value = models.FloatField('Valor')

    def __str__(self):
        return str(self.user) + ' | ' + str(self.market) + ' | ' + self.wallet.dt_updated.strftime('%Y-%m-%d')


class GroupAgg(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    market = models.ForeignKey(Market, on_delete=models.CASCADE)
    group = models.ForeignKey(AssetGroup, on_delete=models.CASCADE)
    cost = models.FloatField('Custo')
    value = models.FloatField('Valor')

    def __str__(self):
        return str(self.user) + ' | ' + str(self.group) + ' | ' + self.wallet.dt_updated.strftime('%Y-%m-%d')

invest/forms.py
from django import forms


class ContentDetailForm(forms.Form):
    quantity = forms.FloatField(label='Quantidade')
    cost = forms.FloatField(label='Custo')
    price = forms.FloatField(label='Cotação')
    value = forms.FloatField(label='Valor')


class NewContentForm(forms.Form):
    quantity = forms.FloatField(label='Quantidade')
    cost = forms.FloatField(label='Custo')
    price = forms.FloatField(label='Cotação')
    value = forms.FloatField(label='Valor')

invest/views.py
import json
import pandas as pd
import yfinance as yf

from datetime import timedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import View
from django.views.generic import DetailView, ListView

from .forms import ContentDetailForm, NewContentForm
from .models import Asset, Content, GroupAgg, Market, MarketAgg, Wallet
from .utils import qs_to_df
from cadastro.models import User
from statement.models import Dividend, Transaction


class IndexView(View):
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        return render(request, 'invest/index.html', {})


class HomeView(LoginRequiredMixin, View):
    login_url = 'cadastro:login'
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        try:
            wallet = Wallet.objects.filter(user_id=request.user).latest('dt_updated')
        except Wallet.DoesNotExist:
            return render(request, 'invest/home/home.html', {})

        market_agg = MarketAgg.objects.filter(wallet_id=wallet.id).order_by('-value')
        markets = [ agg.market for agg in market_agg ]

        group_agg = {}
        group_plot = {}
        for market in markets:
            qs = GroupAgg.objects.filter(wallet_id=wallet.id,
                                         market=market).order_by('-value')
            df = qs_to_df(qs, 'group_id__group', 'value', 'market_id__symbol')
            df.columns = ['group', 'value', 'currency_repr']
            total = df['value'].sum()
            df['pct'] = df['value'].apply(lambda x: 100*x/total)
            group_agg[market] = df.to_dict(orient='records')
            group_plot[market.name] = {
                'x': df['group'].to_list(),
                'y': df['value'].to_list(),
                'currency_symbol': market.symbol
            }

        # Evolução patrimonial
        markets = Market.objects.all()
        wallets = Wallet.objects.filter(user=request.user)

        agg = MarketAgg.objects.filter(user=request.user)
        df = qs_to_df(agg)
        df_value = df.pivot(index='wallet_id',values='value',columns='market_id').reset_index()
        df_value.fillna(0, inplace=True)
        df_value['date'] = df_value['wallet_id'].apply(lambda x: wallets.get(pk=x).dt_updated.strftime('%Y-%m-%d'))

        df['gain'] = df['value']-df['cost']
        df_gain = df.pivot(index='wallet_id', values='gain', columns='market_id').reset_index()
        df_gain.fillna(0, inplace=True)
        df_gain['date'] = df_gain['wallet_id'].apply(lambda x: wallets.get(pk=x).dt_updated.strftime('%Y-%m-%d'))

        history_plot = {
            'date': df_value['date'].to_list(),
            'datasets': []
        }
        gain_plot = {
            'date': df_value['date'].to_list(),
            'datasets': []
        }
        for mkt_id in df['market_id'].unique():
            market = markets.get(pk=mkt_id).name
            currency = markets.get(pk=mkt_id).symbol
            history_plot['datasets'].append({
                'data': df_value[mkt_id].to_list(),
                'label': currency
            })
            gain_plot['datasets'].append({
                'data': df_gain[mkt_id].to_list(),
                'label': currency
            })

        context = {
            'last_updated': wallet.dt_updated,
            'market_agg_table': market_agg,
            'group_agg': group_agg,
            'group_plot': json.dumps(group_plot),
            'history_plot': json.dumps(history_plot),
            'gain_plot': json.dumps(gain_plot)
        }

        return render(request, 'invest/home/home.html', context)


class UpdateWalletView(LoginRequiredMixin, View):
    login_url = 'cadastro:login'
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        user = request.user

        # Consolidate statement
        w, transactions = self.consolidate_transaction_statement(user)

        # Update or create wallet
        current_wallet, previous_wallet_id = self.update_wallet(user)
        if current_wallet is not None:# Update existing wallet for the current month
            for k in w.keys():
                asset_id, bank_id = k.split(':')
                asset_id = int(asset_id)
                bank_id = int(bank_id)
                Content.objects.update_or_create(
                    wallet=current_wallet,
                    user=user,
                    asset_id=asset_id,
                    bank_id=bank_id,
                    defaults={
                        'quantity': w.get(k).get('quantity'),
                        'cost': w.get(k).get('cost'),
                        'price': 0,
                        'dt_updated': current_wallet.dt_created
                    }
                )
            current_wallet.save()# Update field dt_updated

            # Remove assets sold since last update
            Content.objects.filter(wallet=current_wallet, quantity=0).delete()

        else:# Create new wallet
            new_wallet = Wallet.objects.create(user=user, dt_created=timezone.now())
            for k in w.keys():
                asset_id, bank_id = k.split(':')
                asset_id = int(asset_id)
                bank_id = int(bank_id)
                Content.objects.create(
                    wallet=new_wallet,
                    user=user,
                    asset_id=asset_id,
                    bank_id=bank_id,
                    quantity=w.get(k).get('quantity'),
                    cost=w.get(k).get('cost'),
                    price=0,
                    dt_updated=new_wallet.dt_created
                )
            # Remove assets sold
            # TODO: não deveria ser removido no método consolidate_transaction_statement? Criar testes incluindo venda
            Content.objects.filter(wallet=new_wallet, quantity=0).delete()

            # Copiar caixa da carteira anterior
            if previous_wallet_id is not None:
                contents_in_statement = [ f'{t.asset_id}:{t.bank_id}' for t in transactions ]
                contents = Content.objects.filter(wallet_id=previous_wallet_id)
                contents_in_last_wallet = [ f'{c.asset_id}:{c.bank_id}' for c in contents ]
                transfer_content = [ c for c in contents_in_last_wallet if c not in contents_in_statement ]
                for c in transfer_content:
                    asset_id, bank_id = c.split(':')
                    asset_id = int(asset_id)
                    bank_id = int(bank_id)
                    content = contents.get(asset_id=asset_id, bank_id=bank_id)# Asset e bank definem um content unicamente dentro de uma carteira.
                    Content.objects.create(
                        wallet=new_wallet,
                        user=user,
                        asset_id=asset_id,
                        bank_id=bank_id,
                        quantity=content.quantity,
                        cost=content.cost,
                        price=content.price,
                        dt_updated=new_wallet.dt_created
                    )

        return HttpResponseRedirect(reverse('invest:home'))

    def update_wallet(self, user):
        '''
        Returns the wallet to be updated (current month), otherwise none.
        Returns the id of the previous wallet, whatever month it was created (to copy assets inserted manually).
        '''
        qs = Wallet.objects.filter(user=user).order_by('-dt_created')[:1]
        now = timezone.now()
        previous_wallet_id = None
        if qs.exists():
            wallet = qs[0]
            previous_wallet_id = wallet.id
            if wallet.dt_created.month == now.month:# Update existing wallet
                create_new_wallet = False
                return wallet, None
        return None, previous_wallet_id

    def consolidate_transaction_statement(self, user):
        # Key -> asset.id:bank.id
        # {
        #     '1:1': {'quantity': 1.0, 'cost': 10.0},
        #     '2:1': {'quantity': 2.0, 'cost': 22.0}
        # }
        transactions = Transaction.objects.filter(user=user)
        transactions = transactions.order_by('date')
        w = {}
        for t in transactions:
            content_key = f'{t.asset.id}:{t.bank.id}'
            if t.event == 'COMPRA' or t.event == 'SUBSCRICAO':
                cost = t.value + t.fee
                if content_key in w:
                    w[content_key]['quantity'] += t.quantity
                    w[content_key]['cost'] += cost
                else:
                    w[content_key] = {
                        'quantity': t.quantity,
                        'cost': cost
                    }
            elif t.event == 'VENDA':
                avg_cost = w[content_key]['cost']/w[content_key]['quantity']
                value_sold = round(avg_cost * t.quantity, 2)
                w[content_key]['cost'] -= value_sold
                w[content_key]['quantity'] -= t.quantity
            elif t.event == 'DESDOBRAMENTO':
                w[content_key]['quantity'] *= t.post_split/t.pre_split
            elif t.event == 'GRUPAMENTO':
                w[content_key]['quantity'] = round(w[content_key]['quantity']*t.post_split/t.pre_split, 5)
            elif t.event == 'BONIFICACAO':
                cost = t.value + t.fee
                w[content_key]['quantity'] += t.quantity
                w[content_key]['cost'] += cost
            elif t.event == 'AMORTIZACAO':
                w[content_key]['cost'] -= t.value
            else:
                print(f'Evento de {t.asset} não suportado em {t.date.strftime("%Y-%m-%d")}: {t.event}')
        return w, transactions


def YFdata(ticker_list, replace_ticker=False):
    end_date = timezone.now()
    start_date = end_date-timedelta(days=7)
    data = (

invest/templates/invest/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Invest{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'invest/bootstrap/bootstrap.min.css' %}">

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static 'invest/js/plot.js' %}"></script>
</head>
<body>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
        <div class="container-fluid">
            {% if user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'invest:home' %}">Invest</a>
            {% else %}
                <a class="navbar-brand" href="{% url 'invest:index' %}">Invest</a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-toggler" aria-controls="navbar-toggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar-toggler">
                <ul class="navbar-nav ms-auto flex-nowrap">
                    {% if user.is_authenticated %}
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'cadastro:change_password' %}">Bem-vindo(a) {{ user.first_name }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Sair</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cadastro:login' %}">Entrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cadastro:register' %}">Registrar-se</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page content -->
    <section>
        {% block content %}
        {% endblock %}
    </section>

    <!-- Footer -->
    <footer class="container pt-3 mt-4 text-muted border-top">
        &copy; 2023
    </footer>

    <script src="{% static 'invest/bootstrap/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

invest/templates/invest/base_logged.html
{% extends 'invest/base.html' %}


{% load static %}


{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Sidebar -->
        <div class="col-sm-3 col-md-2 sidebar bg-light">
            {% block sidebar %}
            {% endblock %}
            <ul>
                <li>
                    <a href="{% url 'invest:home' %}">Painel</a>
                </li>
                <li>
                    <a href="{% url 'invest:content_list' %}">Investimentos</a>
                </li>
                <li>
                    <a href="{% url 'invest:dividend_list' %}">Dividendos</a>
                </li>
                <li>
                    <a href="{% url 'invest:update_wallet' %}">Consolidar carteira</a>
                </li>
                <li>
                    <a href="{% url 'invest:update_content_value' %}">Atualizar valores</a>
                </li>
            </ul>
        </div>

        <!-- Main content -->
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block logged_content %}
            {% endblock %}
        </div>

    </div>
</div>

{% endblock %}

invest/templates/invest/content_detail.html
{% extends 'invest/base_logged.html' %}


{% load numberformat %}


{% block logged_content %}

<h1 class="border-bottom">{{ asset_name }}</h1>
<p>{{ description }}</p>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <canvas id="value-chart" width="400" height="200"></canvas>
        </div>
        <div class="col-md-6">
            <p>Quantidade: {{ content.quantity }}</p>
            <p>Custo: {{ content.cost|currency:currency_symbol }}</p>
            <p>Valor: {{ content.value|currency:currency_symbol }}</p>
            <p>Custo médio: {{ content.cm|currency:currency_symbol }}</p>
            <p>Cotação: {{ content.price|currency:currency_symbol }}</p>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <canvas id="dividend-chart" width="400" height="200"></canvas>
        </div>
        <div class="col-md-6 table-responsive table-fix-head">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Data</th><th>Cotação</th><th>Dividendo</th><th>DY</th>
                    </tr>
                </thead>
                <tbody>
                    {% if dividend %}
                        {% for row in dividend %}
                            <tr>
                                <td>{{ row.date }}</td>
                                <td>-</td>
                                <td>{{ row.value|currency:currency_symbol }}</td>
                                <td>-</td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    if ('{{ value_history_json }}') {
        const [x, y] = djangoQuerysetDeserializer(
            '{{ value_history_json|escapejs }}', 'dt_updated', 'value'
        )
        var datasets = [{data: y}]
        var ctx = document.getElementById('value-chart')
        var ylabel = '{{ currency_symbol|escapejs }}'
        lineplot(x, datasets, ctx, {ylabel: ylabel})
    }

    if ('{{ dividend_json }}') {
        const [x, y] = djangoQuerysetDeserializer(
            '{{ dividend_json|escapejs }}', 'date', 'value'
        )
        var datasets = [{data: y}]
        var ctx = document.getElementById('dividend-chart')
        var ylabel = '{{ currency_symbol|escapejs }}'
        barplot(x, datasets, ctx, {ylabel: ylabel})
    }
</script>

{% endblock %}

invest/templates/invest/current_wallet.html
{% extends 'invest/base_logged.html' %}


{% load numberformat %}


{% block logged_content %}

<h1 class="border-bottom">Meus investimentos</h1>

<!-- Info -->
<div class="mb-3">
    <p>{{ number_of_assets }} investimentos na sua carteira.</p>
    <p>Última atualização em {{ date }}.</p>
</div>

<!-- Filtros -->
<div class="mb-3">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <select class="form-select" id="market_selector">
                    <option value="ALL">- Todos os locais -</option>
                    {% for market in markets %}
                        <option value="market{{ market.0 }}">{{ market.1 }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-4">
                <select class="form-select" id="type_selector">
                    <option value="ALL">- Todos os tipos -</option>
                    {% for type in types %}
                        <option value="type{{ type.0 }}">{{ type.1 }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-4">
                <select class="form-select" id="group_selector">
                    <option value="ALL">- Todos os grupos -</option>
                    {% for group in groups %}
                        <option value="group{{ group.0 }}">{{ group.1 }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>
</div>

<!-- Assets list -->
<div>
    <div class="mb-3">
        <button type="button" class="btn btn-outline-dark btn-sm" data-bs-toggle="modal" data-bs-target="#new-content-modal">+</button>
    </div>
    {% for invest in wallet_contents %}
        <div class="card mb-3" id="market{{ invest.asset.market.id }} type{{ invest.asset.type.id }} group{{ invest.asset.group.id }}">
            <a class="stretched-link" href="{% url 'invest:content_detail' invest.id %}"></a>
            <div class="card-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-4">
                            <p><strong>{{ invest.asset.name }}</strong></p>
                            <p>Quantidade: {{ invest.quantity }}</p>
                        </div>
                        <div class="col-md-4">
                            <p>{{ invest.asset.type }}</p>
                            <p>Valor: {{ invest.value|currency:invest.asset.market.symbol }}</p>
                        </div>
                        <div class="col-md-4">
                            <p>{{ invest.asset.group }} - {{ invest.asset.market }}</p>
                            {% if invest.asset.expiration_date is not None %}
                                <p>Vencimento: {{ invest.asset.expiration_date }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

<!-- Modal -->
{% include 'invest/new_content_modal.html' %}

<script>
    function filterCards () {
        var marketFilterState = document.getElementById("market_selector").value
        var typeFilterState = document.getElementById("type_selector").value
        var groupFilterState = document.getElementById("group_selector").value
        document.querySelectorAll(".card").forEach(el => {
            var cardIDs = el.id.split(" ")
            el.style.display = "block"
            if (marketFilterState != "ALL" && !cardIDs.includes(marketFilterState)) {
                el.style.display = "none"
            }
            if (typeFilterState != "ALL" && !cardIDs.includes(typeFilterState)) {
                el.style.display = "none"
            }
            if (groupFilterState != "ALL" && !cardIDs.includes(groupFilterState)) {
                el.style.display = "none"
            }
        })
    }
    document.getElementById("market_selector").addEventListener("change", filterCards)
    document.getElementById("type_selector").addEventListener("change", filterCards)
    document.getElementById("group_selector").addEventListener("change", filterCards)
</script>

{% endblock %}

invest/templates/invest/dividend_detail.html
{% extends 'invest/base_logged.html' %}


{% load numberformat %}


{% block logged_content %}

<h1 class="border-bottom">Dividendos de {{ dividend.asset.name }}</h1>
<p>{{ dividend.asset.description }}</p>

<div>
    <ul>
        <li>Data do pagamento: {{ dividend.date }}</li>
        <li>Valor: {{ dividend.value|currency:dividend.asset.market.symbol }}</li>
        <li>Recebido em: {{ dividend.bank.name }}</li>
    </ul>
</div>

{% endblock %}

invest/templates/invest/dividend_list.html
{% extends 'invest/base_logged.html' %}


{% load numberformat %}


{% block logged_content %}

<h1 class="border-bottom">Meus dividendos</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 table-responsive table-fix-head" style="max-height: 400px;">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Local</th><th>Dividendo</th><th>DY</th><th>YoC</th>
                    </tr>
                </thead>
                <tbody>
                    {% for market in market_agg %}
                    <tr>
                        <td>{{ market.market }}</td>
                        <td>{{ market.dividend|currency:market.currency }}</td>
                        <td>{{ market.dy|number:2 }}%</td>
                        <td>{{ market.yoc|number:2 }}%</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div>
    <ul>
        {% for dividend in dividend_list %}
        <li>
            <a href="{% url 'invest:dividend_detail' dividend.id %}">&#128712;</a>
            {{ dividend.date }} {{ dividend.asset }} {{ dividend.bank }} {{ dividend.value|currency:dividend.asset.market.symbol }}
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

invest/templates/invest/index.html
{% extends 'invest/base.html' %}


{% block content %}

<div class="container py-4">

    <div class="p-5 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">Bem-vindo à Invest!</h1>
            <p class="col-md-8 fs-4">Uma plataforma daora.</p>
        </div>
    </div>

    <div class="row align-items-md-stretch">
        <div class="col-md-6">
            <div class="h-100 p-5 text-bg-dark rounded-3">
            <h2>Entrar</h2>
            <p>Swap the background-color utility.</p>
            <a class="btn btn-outline-light" href="{% url 'cadastro:login' %}">Entrar</a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="h-100 p-5 bg-light border rounded-3">
            <h2>Registrar-se</h2>
            <p>Or, keep it light and add a border.</p>
            <a class="btn btn-outline-secondary" href="{% url 'cadastro:register' %}">Registrar-se</a>
            </div>
        </div>
    </div>

</div>

{% endblock %}